"""Increase effort

Revision ID: 85b8de4ed2d5
Revises: 9a071f111089
Create Date: 2023-12-01 13:43:10.658809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b8de4ed2d5'
down_revision: Union[str, None] = '9a071f111089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('increase_effort', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'increase_effort')
    # ### end Alembic commands ###
