"""Rename

Revision ID: f02ef271f082
Revises: 85b8de4ed2d5
Create Date: 2023-12-01 16:45:48.597611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f02ef271f082'
down_revision: Union[str, None] = '85b8de4ed2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('alternative_exercise', sa.String(length=100), nullable=True))
    op.drop_column('activities', 'alternate_exercise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('alternate_exercise', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('activities', 'alternative_exercise')
    # ### end Alembic commands ###
